version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    environment:
      - MONGODB_URI=mongodb+srv://justsomefaltuka:Z25sn5ClgNVzbp71@cluster0.f2azosj.mongodb.net/streaming-backend
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  streaming:
    build:
      context: ./streaming
    container_name: streaming
    ports:
      - "1935:1935" # RTMP
      - "8080:80" # HLS HTTP
    volumes:
      - ./streaming/hls:/var/www/hls
    restart: always

volumes:
  mongo-data:
